/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        //lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png")));
        //Border logo = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        //lblicon.setBorder(logo);
        
        //Border name = BorderFactory.createMatteBorder(0,0,3,0, Color.white);
        //lblname.setBorder(name);
        
        Border menu = BorderFactory.createMatteBorder(0,0,1,0, Color.yellow);
        lblp.setBorder(menu);
        lblptype.setBorder(menu);
        lblpimages.setBorder(menu);
        lblowner.setBorder(menu);
        lblclient.setBorder(menu);
        lblsales.setBorder(menu);
        lbllogout.setBorder(menu);
        
        
        /*
         
          Add foreign keys to the database
          1 foreign key between table property_type & properties
          ALTER TABLE properties ADD CONSTRAINT fk_type_id FOREIGN KEY (type) REFERENCES property_type (id) on UPDATE CASCADE on DELETE CASCADE;
        
          2 foreign key between table properties & owners
          ALTER TABLE properties ADD CONSTRAINT fk_owner_id FOREIGN KEY (ownerid) REFERENCES owners (id) on UPDATE CASCADE on DELETE CASCADE;
        
          3 foreign key between table properties & property_images
          ALTER TABLE property_images ADD CONSTRAINT fk_property_id FOREIGN KEY (property_id) REFERENCES properties (id) on UPDATE CASCADE on DELETE CASCADE;
        
          4 foreign key between table sales & properties
          5 foreign key between table sales & clients
          ALTER TABLE sales ADD CONSTRAINT fk_sale_property_id FOREIGN KEY (property_id) REFERENCES properties (id) on UPDATE CASCADE on DELETE CASCADE;
          ALTER TABLE sales ADD CONSTRAINT fk_sale_client_id FOREIGN KEY (client_id) REFERENCES clients (id) on UPDATE CASCADE on DELETE CASCADE;
          
        */
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblclient = new javax.swing.JLabel();
        lblp = new javax.swing.JLabel();
        lblptype = new javax.swing.JLabel();
        lblpimages = new javax.swing.JLabel();
        lblowner = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        lblsales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1600, 860));
        setMinimumSize(new java.awt.Dimension(1600, 800));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1600, 860));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 860));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 860));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 170));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 170));

        lblclient.setBackground(new java.awt.Color(102, 102, 102));
        lblclient.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblclient.setForeground(new java.awt.Color(255, 255, 255));
        lblclient.setText("   Client");
        lblclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblclient.setOpaque(true);
        lblclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblclientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblclientMouseExited(evt);
            }
        });
        jPanel2.add(lblclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 240, 30));

        lblp.setBackground(new java.awt.Color(102, 102, 102));
        lblp.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblp.setForeground(new java.awt.Color(255, 255, 255));
        lblp.setText("   Property");
        lblp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblp.setOpaque(true);
        lblp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpMouseExited(evt);
            }
        });
        jPanel2.add(lblp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, 30));

        lblptype.setBackground(new java.awt.Color(102, 102, 102));
        lblptype.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblptype.setForeground(new java.awt.Color(255, 255, 255));
        lblptype.setText("   Property-Type");
        lblptype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblptype.setOpaque(true);
        lblptype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblptypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblptypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblptypeMouseExited(evt);
            }
        });
        jPanel2.add(lblptype, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 240, 30));

        lblpimages.setBackground(new java.awt.Color(102, 102, 102));
        lblpimages.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblpimages.setForeground(new java.awt.Color(255, 255, 255));
        lblpimages.setText("   Property-Images");
        lblpimages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblpimages.setOpaque(true);
        lblpimages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpimagesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpimagesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpimagesMouseExited(evt);
            }
        });
        jPanel2.add(lblpimages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 30));

        lblowner.setBackground(new java.awt.Color(102, 102, 102));
        lblowner.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblowner.setForeground(new java.awt.Color(255, 255, 255));
        lblowner.setText("   Owner");
        lblowner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblowner.setOpaque(true);
        lblowner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblownerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblownerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblownerMouseExited(evt);
            }
        });
        jPanel2.add(lblowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 240, 30));

        lbllogout.setBackground(new java.awt.Color(102, 102, 102));
        lbllogout.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setText("   Logout");
        lbllogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllogout.setOpaque(true);
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogoutMouseExited(evt);
            }
        });
        jPanel2.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 240, 30));

        lblsales.setBackground(new java.awt.Color(102, 102, 102));
        lblsales.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblsales.setForeground(new java.awt.Color(255, 255, 255));
        lblsales.setText("   Sales");
        lblsales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsales.setOpaque(true);
        lblsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsalesMouseExited(evt);
            }
        });
        jPanel2.add(lblsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 240, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 860));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseEntered
        
        lblp.setBackground(Color.white);
        lblp.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_lblpMouseEntered

    private void lblpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseExited
        
        lblp.setBackground(new Color(102,102,102));
        lblp.setForeground(Color.white);
    }//GEN-LAST:event_lblpMouseExited

    private void lblptypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblptypeMouseEntered
        
        lblptype.setBackground(Color.white);
        lblptype.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_lblptypeMouseEntered

    private void lblptypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblptypeMouseExited
        
        lblptype.setBackground(new Color(102,102,102));
        lblptype.setForeground(Color.white);
        
    }//GEN-LAST:event_lblptypeMouseExited

    private void lblpimagesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpimagesMouseEntered
        
        lblpimages.setBackground(Color.white);
        lblpimages.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_lblpimagesMouseEntered

    private void lblpimagesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpimagesMouseExited
        
        lblpimages.setBackground(new Color(102,102,102));
        lblpimages.setForeground(Color.white);
    }//GEN-LAST:event_lblpimagesMouseExited

    private void lblownerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblownerMouseEntered
        
        lblowner.setBackground(Color.white);
        lblowner.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_lblownerMouseEntered

    private void lblownerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblownerMouseExited
        
        lblowner.setBackground(new Color(102,102,102));
        lblowner.setForeground(Color.white);
    }//GEN-LAST:event_lblownerMouseExited

    private void lblclientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclientMouseEntered
        
        lblclient.setBackground(Color.white);
        lblclient.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_lblclientMouseEntered

    private void lblclientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclientMouseExited
        
        lblclient.setBackground(new Color(102,102,102));
        lblclient.setForeground(Color.white);
    }//GEN-LAST:event_lblclientMouseExited

    private void lblptypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblptypeMouseClicked
        
        //open the property type form
        PropertyType ptype = new PropertyType();
        ptype.setVisible(true);
        ptype.pack();
        ptype.setLocationRelativeTo(null);
        ptype.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_lblptypeMouseClicked

    private void lblownerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblownerMouseClicked
        
        //open the owner form
        Owner owner = new Owner();
        owner.setVisible(true);
        owner.pack();
        owner.setLocationRelativeTo(null);
        owner.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_lblownerMouseClicked

    private void lblclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclientMouseClicked
        
        //open the client form
        Client client = new Client();
        client.setVisible(true);
        client.pack();
        client.setLocationRelativeTo(null);
        client.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_lblclientMouseClicked

    private void lblpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseClicked
       
        //open the property form
        Property property = new Property();
        property.setVisible(true);
        property.pack();
        property.setLocationRelativeTo(null);
        property.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_lblpMouseClicked

    private void lblpimagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpimagesMouseClicked
        
        //open the propertyImages form
        PropertyImages propertyImages = new PropertyImages();
        propertyImages.setVisible(true);
        propertyImages.pack();
        propertyImages.setLocationRelativeTo(null);
        propertyImages.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_lblpimagesMouseClicked

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
        
        int a = JOptionPane.showConfirmDialog(rootPane, "Do you want to logout ", "Logout", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            setVisible(false);
            new Login().setVisible(true);
        }
        
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void lbllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseEntered
        
        lbllogout.setBackground(Color.white);
        lbllogout.setForeground(new Color(102,102,102));
        
    }//GEN-LAST:event_lbllogoutMouseEntered

    private void lbllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseExited
        
        lbllogout.setBackground(new Color(102,102,102));
        lbllogout.setForeground(Color.white);
        
    }//GEN-LAST:event_lbllogoutMouseExited

    private void lblsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalesMouseClicked
        
        //open the sales form
        Sales sale = new Sales();
        sale.setVisible(true);
        sale.pack();
        sale.setLocationRelativeTo(null);
        sale.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_lblsalesMouseClicked

    private void lblsalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalesMouseEntered
        
        lblsales.setBackground(Color.white);
        lblsales.setForeground(new Color(102,102,102));
        
    }//GEN-LAST:event_lblsalesMouseEntered

    private void lblsalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalesMouseExited
       
        lblsales.setBackground(new Color(102,102,102));
        lblsales.setForeground(Color.white);
        
    }//GEN-LAST:event_lblsalesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblclient;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblowner;
    private javax.swing.JLabel lblp;
    private javax.swing.JLabel lblpimages;
    private javax.swing.JLabel lblptype;
    private javax.swing.JLabel lblsales;
    // End of variables declaration//GEN-END:variables
}
