/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class ShowPropImage extends javax.swing.JFrame {

    /**
     * Creates new form ShowPropImage
     */
    
    //get the property id
    static int propertyId;
    
    //images list
    ArrayList<byte[]> imageList;
    
    //the image index
    int index=0;
    
    public ShowPropImage(int pId) {
        initComponents();
        
        this.propertyId = pId;
        
        //set border to the image label
        Border imageLabel = BorderFactory.createMatteBorder(1,1,1,1, new Color(0,0,0));
        lblimage.setBorder(imageLabel);
        
        //set border to the previous & next labels
        Border preLabel = BorderFactory.createMatteBorder(2,2,2,2, new Color(0,255,0));
        lblprevious.setBorder(preLabel);
        lblnext.setBorder(preLabel);
        
        //get the images using the hashmap
        HashMap<byte[], Integer> map = new P_Properties().propertyImageList(propertyId);
        imageList = new ArrayList<>(map.keySet());
        
        displayImage(index);
        
    }
    
    //create a function to display the image by index
    public void displayImage(int imageIndex)
    {
        Image img = new ImageIcon(imageList.get(imageIndex)).getImage().getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        lblimage.setIcon(image);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        lblprevious = new javax.swing.JLabel();
        lblnext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblimage.setBackground(new java.awt.Color(204, 204, 204));
        lblimage.setOpaque(true);

        lblprevious.setBackground(new java.awt.Color(255, 255, 255));
        lblprevious.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblprevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprevious.setText("<");
        lblprevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblprevious.setOpaque(true);
        lblprevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpreviousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpreviousMouseExited(evt);
            }
        });

        lblnext.setBackground(new java.awt.Color(255, 255, 255));
        lblnext.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblnext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnext.setText(">");
        lblnext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblnext.setOpaque(true);
        lblnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblnextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblnextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnext, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnextMouseClicked
        
            //show the next image
            index++;

            if (index >= imageList.size()) {
                index = imageList.size() - 1;
            }

            displayImage(index);
        
    }//GEN-LAST:event_lblnextMouseClicked

    private void lblpreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpreviousMouseClicked
        
       //show the previous image
            index--;

            if (index < 0) {
                index = 0;
            }

            displayImage(index);
        
        
    }//GEN-LAST:event_lblpreviousMouseClicked

    private void lblnextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnextMouseEntered
        
        lblnext.setBackground(Color.orange);
        lblnext.setForeground(Color.white);
        
    }//GEN-LAST:event_lblnextMouseEntered

    private void lblnextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnextMouseExited
        
        lblnext.setBackground(Color.white);
        lblnext.setForeground(Color.black);
        
    }//GEN-LAST:event_lblnextMouseExited

    private void lblpreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpreviousMouseEntered
        
        lblprevious.setBackground(Color.orange);
        lblprevious.setForeground(Color.white);
        
    }//GEN-LAST:event_lblpreviousMouseEntered

    private void lblpreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpreviousMouseExited
        
        lblprevious.setBackground(Color.white);
        lblprevious.setForeground(Color.black);
        
    }//GEN-LAST:event_lblpreviousMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPropImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPropImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPropImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPropImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPropImage(propertyId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblnext;
    private javax.swing.JLabel lblprevious;
    // End of variables declaration//GEN-END:variables
}
